spring:
  application:
    name: SERVICE-SERVER-RABBITMQ
  rabbitmq:
    username: onechain
    password: admin
    virtual-host: onechain
    addresses: 47.75.196.12:5672,47.75.111.155:5672,47.52.130.114:5672
    listener:
      simple:
        auto-startup: true
        retry:
          enabled: true
          max-attempts: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:40001/eureka/
    fetch-registry: true
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
#RabbitMq routingKey配置
onechainmqconf:
  routingKey: updateUserBalance,ethMentionCoinKey,bitcoinTransfer,OTCUpdateUserBalance
  defaultExchange: ctpprodexchange

# 日志配置
#logging:
  #level: info
  #config: classpath:logback/logback-prod.xml