server:
  port: 40001

spring:
  application:
      name: SERVICE-MGR-EUREKA

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:40001/eureka/