eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:40001/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
