eureka:
  client:
    serviceUrl:
      defaultZone: http://ctp.server-mgr-eureka.master.dev:52100/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10